STATS = [
    # ── Batting ───────────────────────────────────────────────────────────────
    {"code": "HR",   "label": "Home Runs",                  "table": "batting",  "column": "HR"},
    {"code": "H",    "label": "Hits",                       "table": "batting",  "column": "H"},
    {"code": "2B",   "label": "Doubles",                    "table": "batting",  "column": "2B"},
    {"code": "3B",   "label": "Triples",                    "table": "batting",  "column": "3B"},
    {"code": "RBI",  "label": "Runs Batted In",             "table": "batting",  "column": "RBI"},
    {"code": "R",    "label": "Runs Scored",                "table": "batting",  "column": "R"},
    {"code": "SB",   "label": "Stolen Bases",               "table": "batting",  "column": "SB"},
    {"code": "BB_B", "label": "Walks (Batter)",             "table": "batting",  "column": "BB"},
    {"code": "SO_B", "label": "Strikeouts (Batter)",        "table": "batting",  "column": "SO"},
    {"code": "AB",   "label": "At Bats",                    "table": "batting",  "column": "AB"},
    {"code": "PA",   "label": "Plate Appearances",          "table": "batting",  "column": "PA"},
    {"code": "G_B",  "label": "Games Played",               "table": "batting",  "column": "G"},
    {"code": "HBP",  "label": "Hit by Pitch",               "table": "batting",  "column": "HBP"},
    {"code": "IBB",  "label": "Intentional Walks (Batter)", "table": "batting",  "column": "IBB"},
    {"code": "SF",   "label": "Sacrifice Flies",            "table": "batting",  "column": "SF"},
    {"code": "SH",   "label": "Sacrifice Hits",             "table": "batting",  "column": "SH"},
    {"code": "GIDP", "label": "Grounded Into Double Play",  "table": "batting",  "column": "GIDP"},
    # ── Pitching ──────────────────────────────────────────────────────────────
    {"code": "W",    "label": "Wins",                       "table": "pitching", "column": "W"},
    {"code": "SO_P", "label": "Strikeouts (Pitcher)",       "table": "pitching", "column": "SO"},
    {"code": "SV",   "label": "Saves",                      "table": "pitching", "column": "SV"},
    {"code": "G_P",  "label": "Games Pitched",              "table": "pitching", "column": "G"},
    {"code": "IP",   "label": "Innings Pitched",            "table": "pitching", "column": "IPouts", "scale": 3},
    {"code": "BB_P", "label": "Walks (Pitcher)",            "table": "pitching", "column": "BB"},
    {"code": "L",    "label": "Losses",                     "table": "pitching", "column": "L"},
    {"code": "CG",   "label": "Complete Games",             "table": "pitching", "column": "CG"},
    {"code": "SHO",  "label": "Shutouts",                   "table": "pitching", "column": "SHO"},
    {"code": "H_P",  "label": "Hits Allowed",               "table": "pitching", "column": "H"},
]
